[build]
  base = "frontend"
  command = "npx convex deploy --cmd 'npm run build'"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_CONVEX_URL = "https://grateful-mastiff-588.convex.cloud"

[[plugins]]
  package = "@netlify/plugin-nextjs"
